version: 2

sources:
  - name: gz_raw_data 
    description: greenweez raw data source

    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of greenweez
        tests:
          - unique: column_name:"(orders_id || '-' || pdt_id)"
        columns:
          - name: date_date
            description: the date of purchase
          - name: orders_id
            description: foreign key to ship
          - name: pdt_id
            description: foreign key to product
          - name: revenue
            description: the amount paid by the customer to buy the product. revenur = quantity * selling_price

      - name: product
        identifier: raw_gz_product
        description: products of greenweez
        columns:
          - name: products_id
            description: primary key for the table
            tests:
              - unique
              - not_null
          - name: purchase_price
            description: purchase price for the product

      - name: ship
        identifier: raw_gz_ship
        description: ships of Greenweez
        columns:
          - name: orders_id
            description: primary key to ship
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: price the customer pays for the shipping
          - name: logcost
            description: cost of preparing the parcel in the warehouse
          - name: ship_cost
            description: shipping cost paid by Greenweez to the transporter
